List<Map<String, String>> codes = <Map<String, String>>[
  <String, String>{"name": "افغانستان", "code": "AF", "dial_code": "+93"},
  <String, String>{"name": "Åland", "code": "AX", "dial_code": "+358"},
  <String, String>{"name": "Shqipëria", "code": "AL", "dial_code": "+355"},
  <String, String>{"name": "الجزائر", "code": "DZ", "dial_code": "+213"},
  <String, String>{
    "name": "American Samoa",
    "code": "AS",
    "dial_code": "+1684",
  },
  <String, String>{"name": "Andorra", "code": "AD", "dial_code": "+376"},
  <String, String>{"name": "Angola", "code": "AO", "dial_code": "+244"},
  <String, String>{"name": "Anguilla", "code": "AI", "dial_code": "+1264"},
  <String, String>{"name": "Antarctica", "code": "AQ", "dial_code": "+672"},
  <String, String>{
    "name": "Antigua and Barbuda",
    "code": "AG",
    "dial_code": "+1268",
  },
  <String, String>{"name": "Argentina", "code": "AR", "dial_code": "+54"},
  <String, String>{"name": "Հայաստան", "code": "AM", "dial_code": "+374"},
  <String, String>{"name": "Aruba", "code": "AW", "dial_code": "+297"},
  <String, String>{"name": "Australia", "code": "AU", "dial_code": "+61"},
  <String, String>{"name": "Österreich", "code": "AT", "dial_code": "+43"},
  <String, String>{"name": "Azərbaycan", "code": "AZ", "dial_code": "+994"},
  <String, String>{"name": "Bahamas", "code": "BS", "dial_code": "+1242"},
  <String, String>{"name": "‏البحرين", "code": "BH", "dial_code": "+973"},
  <String, String>{"name": "Bangladesh", "code": "BD", "dial_code": "+880"},
  <String, String>{"name": "Barbados", "code": "BB", "dial_code": "+1246"},
  <String, String>{"name": "Белару́сь", "code": "BY", "dial_code": "+375"},
  <String, String>{"name": "België", "code": "BE", "dial_code": "+32"},
  <String, String>{"name": "Belize", "code": "BZ", "dial_code": "+501"},
  <String, String>{"name": "Bénin", "code": "BJ", "dial_code": "+229"},
  <String, String>{"name": "Bermuda", "code": "BM", "dial_code": "+1441"},
  <String, String>{"name": "ʼbrug-yul", "code": "BT", "dial_code": "+975"},
  <String, String>{"name": "Bolivia", "code": "BO", "dial_code": "+591"},
  <String, String>{
    "name": "Bosna i Hercegovina",
    "code": "BA",
    "dial_code": "+387",
  },
  <String, String>{"name": "Botswana", "code": "BW", "dial_code": "+267"},
  <String, String>{"name": "Bouvetøya", "code": "BV", "dial_code": "+47"},
  <String, String>{"name": "Brasil", "code": "BR", "dial_code": "+55"},
  <String, String>{
    "name": "British Indian Ocean Territory",
    "code": "IO",
    "dial_code": "+246",
  },
  <String, String>{
    "name": "Negara Brunei Darussalam",
    "code": "BN",
    "dial_code": "+673",
  },
  <String, String>{"name": "България", "code": "BG", "dial_code": "+359"},
  <String, String>{"name": "Burkina Faso", "code": "BF", "dial_code": "+226"},
  <String, String>{"name": "Burundi", "code": "BI", "dial_code": "+257"},
  <String, String>{"name": "Cambodia", "code": "KH", "dial_code": "+855"},
  <String, String>{"name": "Cameroon", "code": "CM", "dial_code": "+237"},
  <String, String>{"name": "Canada", "code": "CA", "dial_code": "+1"},
  <String, String>{"name": "Cabo Verde", "code": "CV", "dial_code": "+238"},
  <String, String>{
    "name": "Cayman Islands",
    "code": "KY",
    "dial_code": "+1345",
  },
  <String, String>{
    "name": "Ködörösêse tî Bêafrîka",
    "code": "CF",
    "dial_code": "+236",
  },
  <String, String>{"name": "Tchad", "code": "TD", "dial_code": "+235"},
  <String, String>{"name": "Chile", "code": "CL", "dial_code": "+56"},
  <String, String>{"name": "中国", "code": "CN", "dial_code": "+86"},
  <String, String>{
    "name": "Christmas Island",
    "code": "CX",
    "dial_code": "+61",
  },
  <String, String>{
    "name": "Cocos (Keeling) Islands",
    "code": "CC",
    "dial_code": "+61",
  },
  <String, String>{"name": "Colombia", "code": "CO", "dial_code": "+57"},
  <String, String>{"name": "Komori", "code": "KM", "dial_code": "+269"},
  <String, String>{
    "name": "République du Congo",
    "code": "CG",
    "dial_code": "+242",
  },
  <String, String>{
    "name": "République démocratique du Congo",
    "code": "CD",
    "dial_code": "+243",
  },
  <String, String>{"name": "Cook Islands", "code": "CK", "dial_code": "+682"},
  <String, String>{"name": "Costa Rica", "code": "CR", "dial_code": "+506"},
  <String, String>{"name": "Côte d'Ivoire", "code": "CI", "dial_code": "+225"},
  <String, String>{"name": "Hrvatska", "code": "HR", "dial_code": "+385"},
  <String, String>{"name": "Cuba", "code": "CU", "dial_code": "+53"},
  <String, String>{"name": "Κύπρος", "code": "CY", "dial_code": "+357"},
  <String, String>{
    "name": "Česká republika",
    "code": "CZ",
    "dial_code": "+420",
  },
  <String, String>{"name": "Danmark", "code": "DK", "dial_code": "+45"},
  <String, String>{"name": "Djibouti", "code": "DJ", "dial_code": "+253"},
  <String, String>{"name": "Dominica", "code": "DM", "dial_code": "+1767"},
  <String, String>{
    "name": "República Dominicana",
    "code": "DO",
    "dial_code": "+1",
  },
  <String, String>{"name": "Ecuador", "code": "EC", "dial_code": "+593"},
  <String, String>{"name": "مصر‎", "code": "EG", "dial_code": "+20"},
  <String, String>{"name": "El Salvador", "code": "SV", "dial_code": "+503"},
  <String, String>{
    "name": "Guinea Ecuatorial",
    "code": "GQ",
    "dial_code": "+240",
  },
  <String, String>{"name": "ኤርትራ", "code": "ER", "dial_code": "+291"},
  <String, String>{"name": "Eesti", "code": "EE", "dial_code": "+372"},
  <String, String>{"name": "ኢትዮጵያ", "code": "ET", "dial_code": "+251"},
  <String, String>{
    "name": "Falkland Islands",
    "code": "FK",
    "dial_code": "+500",
  },
  <String, String>{"name": "Føroyar", "code": "FO", "dial_code": "+298"},
  <String, String>{"name": "Fiji", "code": "FJ", "dial_code": "+679"},
  <String, String>{"name": "Suomi", "code": "FI", "dial_code": "+358"},
  <String, String>{"name": "France", "code": "FR", "dial_code": "+33"},
  <String, String>{
    "name": "Guyane française",
    "code": "GF",
    "dial_code": "+594",
  },
  <String, String>{
    "name": "Polynésie française",
    "code": "PF",
    "dial_code": "+689",
  },
  <String, String>{
    "name": "Territoire des Terres australes et antarctiques fr",
    "code": "TF",
    "dial_code": "+262",
  },
  <String, String>{"name": "Gabon", "code": "GA", "dial_code": "+241"},
  <String, String>{"name": "Gambia", "code": "GM", "dial_code": "+220"},
  <String, String>{"name": "საქართველო", "code": "GE", "dial_code": "+995"},
  <String, String>{"name": "Deutschland", "code": "DE", "dial_code": "+49"},
  <String, String>{"name": "Ghana", "code": "GH", "dial_code": "+233"},
  <String, String>{"name": "Gibraltar", "code": "GI", "dial_code": "+350"},
  <String, String>{"name": "Ελλάδα", "code": "GR", "dial_code": "+30"},
  <String, String>{
    "name": "Kalaallit Nunaat",
    "code": "GL",
    "dial_code": "+299",
  },
  <String, String>{"name": "Grenada", "code": "GD", "dial_code": "+1473"},
  <String, String>{"name": "Guadeloupe", "code": "GP", "dial_code": "+590"},
  <String, String>{"name": "Guam", "code": "GU", "dial_code": "+1671"},
  <String, String>{"name": "Guatemala", "code": "GT", "dial_code": "+502"},
  <String, String>{"name": "Guernsey", "code": "GG", "dial_code": "+44"},
  <String, String>{"name": "Guinée", "code": "GN", "dial_code": "+224"},
  <String, String>{"name": "Guiné-Bissau", "code": "GW", "dial_code": "+245"},
  <String, String>{"name": "Guyana", "code": "GY", "dial_code": "+592"},
  <String, String>{"name": "Haïti", "code": "HT", "dial_code": "+509"},
  <String, String>{
    "name": "Heard Island and McDonald Islands",
    "code": "HM",
    "dial_code": "+0",
  },
  <String, String>{"name": "Vaticano", "code": "VA", "dial_code": "+379"},
  <String, String>{"name": "Honduras", "code": "HN", "dial_code": "+504"},
  <String, String>{"name": "香港", "code": "HK", "dial_code": "+852"},
  <String, String>{"name": "Magyarország", "code": "HU", "dial_code": "+36"},
  <String, String>{"name": "Ísland", "code": "IS", "dial_code": "+354"},
  <String, String>{"name": "भारत", "code": "IN", "dial_code": "+91"},
  <String, String>{"name": "Indonesia", "code": "ID", "dial_code": "+62"},
  <String, String>{"name": "ایران", "code": "IR", "dial_code": "+98"},
  <String, String>{"name": "العراق", "code": "IQ", "dial_code": "+964"},
  <String, String>{"name": "Éire", "code": "IE", "dial_code": "+353"},
  <String, String>{"name": "Isle of Man", "code": "IM", "dial_code": "+44"},
  <String, String>{"name": "ישראל", "code": "IL", "dial_code": "+972"},
  <String, String>{"name": "Italia", "code": "IT", "dial_code": "+39"},
  <String, String>{"name": "Jamaica", "code": "JM", "dial_code": "+1876"},
  <String, String>{"name": "日本", "code": "JP", "dial_code": "+81"},
  <String, String>{"name": "Jersey", "code": "JE", "dial_code": "+44"},
  <String, String>{"name": "الأردن", "code": "JO", "dial_code": "+962"},
  <String, String>{"name": "Қазақстан", "code": "KZ", "dial_code": "+7"},
  <String, String>{"name": "Kenya", "code": "KE", "dial_code": "+254"},
  <String, String>{"name": "Kiribati", "code": "KI", "dial_code": "+686"},
  <String, String>{"name": "북한", "code": "KP", "dial_code": "+850"},
  <String, String>{"name": "대한민국", "code": "KR", "dial_code": "+82"},
  <String, String>{
    "name": "Republika e Kosovës",
    "code": "XK",
    "dial_code": "+383",
  },
  <String, String>{"name": "الكويت", "code": "KW", "dial_code": "+965"},
  <String, String>{"name": "Кыргызстан", "code": "KG", "dial_code": "+996"},
  <String, String>{"name": "ສປປລາວ", "code": "LA", "dial_code": "+856"},
  <String, String>{"name": "Latvija", "code": "LV", "dial_code": "+371"},
  <String, String>{"name": "لبنان", "code": "LB", "dial_code": "+961"},
  <String, String>{"name": "Lesotho", "code": "LS", "dial_code": "+266"},
  <String, String>{"name": "Liberia", "code": "LR", "dial_code": "+231"},
  <String, String>{"name": "‏ليبيا", "code": "LY", "dial_code": "+218"},
  <String, String>{"name": "Liechtenstein", "code": "LI", "dial_code": "+423"},
  <String, String>{"name": "Lietuva", "code": "LT", "dial_code": "+370"},
  <String, String>{"name": "Luxembourg", "code": "LU", "dial_code": "+352"},
  <String, String>{"name": "澳門", "code": "MO", "dial_code": "+853"},
  <String, String>{"name": "Македонија", "code": "MK", "dial_code": "+389"},
  <String, String>{"name": "Madagasikara", "code": "MG", "dial_code": "+261"},
  <String, String>{"name": "Malawi", "code": "MW", "dial_code": "+265"},
  <String, String>{"name": "Malaysia", "code": "MY", "dial_code": "+60"},
  <String, String>{"name": "Maldives", "code": "MV", "dial_code": "+960"},
  <String, String>{"name": "Mali", "code": "ML", "dial_code": "+223"},
  <String, String>{"name": "Malta", "code": "MT", "dial_code": "+356"},
  <String, String>{"name": "M̧ajeļ", "code": "MH", "dial_code": "+692"},
  <String, String>{"name": "Martinique", "code": "MQ", "dial_code": "+596"},
  <String, String>{"name": "موريتانيا", "code": "MR", "dial_code": "+222"},
  <String, String>{"name": "Maurice", "code": "MU", "dial_code": "+230"},
  <String, String>{"name": "Mayotte", "code": "YT", "dial_code": "+262"},
  <String, String>{"name": "México", "code": "MX", "dial_code": "+52"},
  <String, String>{"name": "Micronesia", "code": "FM", "dial_code": "+691"},
  <String, String>{"name": "Moldova", "code": "MD", "dial_code": "+373"},
  <String, String>{"name": "Monaco", "code": "MC", "dial_code": "+377"},
  <String, String>{"name": "Монгол улс", "code": "MN", "dial_code": "+976"},
  <String, String>{"name": "Црна Гора", "code": "ME", "dial_code": "+382"},
  <String, String>{"name": "Montserrat", "code": "MS", "dial_code": "+1664"},
  <String, String>{"name": "المغرب", "code": "MA", "dial_code": "+212"},
  <String, String>{"name": "Moçambique", "code": "MZ", "dial_code": "+258"},
  <String, String>{"name": "Myanmar", "code": "MM", "dial_code": "+95"},
  <String, String>{"name": "Namibia", "code": "NA", "dial_code": "+264"},
  <String, String>{"name": "Nauru", "code": "NR", "dial_code": "+674"},
  <String, String>{"name": "नपल", "code": "NP", "dial_code": "+977"},
  <String, String>{"name": "Nederland", "code": "NL", "dial_code": "+31"},
  <String, String>{
    "name": "Netherlands Antilles",
    "code": "AN",
    "dial_code": "+599",
  },
  <String, String>{
    "name": "Nouvelle-Calédonie",
    "code": "NC",
    "dial_code": "+687",
  },
  <String, String>{"name": "New Zealand", "code": "NZ", "dial_code": "+64"},
  <String, String>{"name": "Nicaragua", "code": "NI", "dial_code": "+505"},
  <String, String>{"name": "Niger", "code": "NE", "dial_code": "+227"},
  <String, String>{"name": "Nigeria", "code": "NG", "dial_code": "+234"},
  <String, String>{"name": "Niuē", "code": "NU", "dial_code": "+683"},
  <String, String>{"name": "Norfolk Island", "code": "NF", "dial_code": "+672"},
  <String, String>{
    "name": "Northern Mariana Islands",
    "code": "MP",
    "dial_code": "+1670",
  },
  <String, String>{"name": "Norge", "code": "NO", "dial_code": "+47"},
  <String, String>{"name": "عمان", "code": "OM", "dial_code": "+968"},
  <String, String>{"name": "Pakistan", "code": "PK", "dial_code": "+92"},
  <String, String>{"name": "Palau", "code": "PW", "dial_code": "+680"},
  <String, String>{"name": "فلسطين", "code": "PS", "dial_code": "+970"},
  <String, String>{"name": "Panamá", "code": "PA", "dial_code": "+507"},
  <String, String>{"name": "Papua Niugini", "code": "PG", "dial_code": "+675"},
  <String, String>{"name": "Paraguay", "code": "PY", "dial_code": "+595"},
  <String, String>{"name": "Perú", "code": "PE", "dial_code": "+51"},
  <String, String>{"name": "Pilipinas", "code": "PH", "dial_code": "+63"},
  <String, String>{
    "name": "Pitcairn Islands",
    "code": "PN",
    "dial_code": "+64",
  },
  <String, String>{"name": "Polska", "code": "PL", "dial_code": "+48"},
  <String, String>{"name": "Portugal", "code": "PT", "dial_code": "+351"},
  <String, String>{"name": "Puerto Rico", "code": "PR", "dial_code": "+1939"},
  <String, String>{"name": "Puerto Rico", "code": "PR", "dial_code": "+1787"},
  <String, String>{"name": "قطر", "code": "QA", "dial_code": "+974"},
  <String, String>{"name": "România", "code": "RO", "dial_code": "+40"},
  <String, String>{"name": "Россия", "code": "RU", "dial_code": "+7"},
  <String, String>{"name": "Rwanda", "code": "RW", "dial_code": "+250"},
  <String, String>{"name": "La Réunion", "code": "RE", "dial_code": "+262"},
  <String, String>{
    "name": "Saint-Barthélemy",
    "code": "BL",
    "dial_code": "+590",
  },
  <String, String>{"name": "Saint Helena", "code": "SH", "dial_code": "+290"},
  <String, String>{
    "name": "Saint Kitts and Nevis",
    "code": "KN",
    "dial_code": "+1869",
  },
  <String, String>{"name": "Saint Lucia", "code": "LC", "dial_code": "+1758"},
  <String, String>{"name": "Saint-Martin", "code": "MF", "dial_code": "+590"},
  <String, String>{
    "name": "Saint-Pierre-et-Miquelon",
    "code": "PM",
    "dial_code": "+508",
  },
  <String, String>{
    "name": "Saint Vincent and the Grenadines",
    "code": "VC",
    "dial_code": "+1784",
  },
  <String, String>{"name": "Samoa", "code": "WS", "dial_code": "+685"},
  <String, String>{"name": "San Marino", "code": "SM", "dial_code": "+378"},
  <String, String>{
    "name": "São Tomé e Príncipe",
    "code": "ST",
    "dial_code": "+239",
  },
  <String, String>{
    "name": "العربية السعودية",
    "code": "SA",
    "dial_code": "+966",
  },
  <String, String>{"name": "Sénégal", "code": "SN", "dial_code": "+221"},
  <String, String>{"name": "Србија", "code": "RS", "dial_code": "+381"},
  <String, String>{"name": "Seychelles", "code": "SC", "dial_code": "+248"},
  <String, String>{"name": "Sierra Leone", "code": "SL", "dial_code": "+232"},
  <String, String>{"name": "Singapore", "code": "SG", "dial_code": "+65"},
  <String, String>{"name": "Slovensko", "code": "SK", "dial_code": "+421"},
  <String, String>{"name": "Slovenija", "code": "SI", "dial_code": "+386"},
  <String, String>{
    "name": "Solomon Islands",
    "code": "SB",
    "dial_code": "+677",
  },
  <String, String>{"name": "Soomaaliya", "code": "SO", "dial_code": "+252"},
  <String, String>{"name": "South Africa", "code": "ZA", "dial_code": "+27"},
  <String, String>{"name": "South Sudan", "code": "SS", "dial_code": "+211"},
  <String, String>{"name": "South Georgia", "code": "GS", "dial_code": "+500"},
  <String, String>{"name": "España", "code": "ES", "dial_code": "+34"},
  <String, String>{"name": "Sri Lanka", "code": "LK", "dial_code": "+94"},
  <String, String>{"name": "السودان", "code": "SD", "dial_code": "+249"},
  <String, String>{"name": "Suriname", "code": "SR", "dial_code": "+597"},
  <String, String>{
    "name": "Svalbard og Jan Mayen",
    "code": "SJ",
    "dial_code": "+47",
  },
  <String, String>{"name": "Swaziland", "code": "SZ", "dial_code": "+268"},
  <String, String>{"name": "Sverige", "code": "SE", "dial_code": "+46"},
  <String, String>{"name": "Schweiz", "code": "CH", "dial_code": "+41"},
  <String, String>{"name": "سوريا", "code": "SY", "dial_code": "+963"},
  <String, String>{"name": "臺灣", "code": "TW", "dial_code": "+886"},
  <String, String>{"name": "Тоҷикистон", "code": "TJ", "dial_code": "+992"},
  <String, String>{"name": "Tanzania", "code": "TZ", "dial_code": "+255"},
  <String, String>{"name": "ประเทศไทย", "code": "TH", "dial_code": "+66"},
  <String, String>{"name": "Timor-Leste", "code": "TL", "dial_code": "+670"},
  <String, String>{"name": "Togo", "code": "TG", "dial_code": "+228"},
  <String, String>{"name": "Tokelau", "code": "TK", "dial_code": "+690"},
  <String, String>{"name": "Tonga", "code": "TO", "dial_code": "+676"},
  <String, String>{
    "name": "Trinidad and Tobago",
    "code": "TT",
    "dial_code": "+1868",
  },
  <String, String>{"name": "تونس", "code": "TN", "dial_code": "+216"},
  <String, String>{"name": "Türkiye", "code": "TR", "dial_code": "+90"},
  <String, String>{"name": "Türkmenistan", "code": "TM", "dial_code": "+993"},
  <String, String>{
    "name": "Turks and Caicos Islands",
    "code": "TC",
    "dial_code": "+1649",
  },
  <String, String>{"name": "Tuvalu", "code": "TV", "dial_code": "+688"},
  <String, String>{"name": "Uganda", "code": "UG", "dial_code": "+256"},
  <String, String>{"name": "Україна", "code": "UA", "dial_code": "+380"},
  <String, String>{
    "name": "United Arab Emirates",
    "code": "AE",
    "dial_code": "+971",
  },
  <String, String>{"name": "United Kingdom", "code": "GB", "dial_code": "+44"},
  <String, String>{"name": "United States", "code": "US", "dial_code": "+1"},
  <String, String>{"name": "Uruguay", "code": "UY", "dial_code": "+598"},
  <String, String>{"name": "O‘zbekiston", "code": "UZ", "dial_code": "+998"},
  <String, String>{"name": "Vanuatu", "code": "VU", "dial_code": "+678"},
  <String, String>{"name": "Venezuela", "code": "VE", "dial_code": "+58"},
  <String, String>{"name": "Việt Nam", "code": "VN", "dial_code": "+84"},
  <String, String>{
    "name": "British Virgin Islands",
    "code": "VG",
    "dial_code": "+1284",
  },
  <String, String>{
    "name": "United States Virgin Islands",
    "code": "VI",
    "dial_code": "+1340",
  },
  <String, String>{
    "name": "Wallis et Futuna",
    "code": "WF",
    "dial_code": "+681",
  },
  <String, String>{"name": "اليَمَن", "code": "YE", "dial_code": "+967"},
  <String, String>{"name": "Zambia", "code": "ZM", "dial_code": "+260"},
  <String, String>{"name": "Zimbabwe", "code": "ZW", "dial_code": "+263"},
];
