Map<String, String> arAe = <String, String>{
  "app_name": "جمع البيانات",
  "loginWithYourPhoneNumber": "تسجيل الدخول برقم هاتفك",
  "mobile_number": "رقم الجوال",
  "welcome_back": "مرحبًا بعودتك",
  "verifyPhoneNumber": "تأكيد رقم الجوال",
  "enterCodeToVerifyPhoneNumber":
      "أدخل الرمز المكون من 4 أرقام المرسل عبر الرسائل القصيرة لتأكيد رقم هاتفك",
  "editPhoneNumber": "تعديل رقم هاتفك؟",
  "verifiedOTP": "تم التحقق من الرمز",
  "didNotReceiveCode": "لم يصلك الرمز؟",
  "resendInXSec": "إعادة الإرسال خلال @otp ثانية",
  "oops": "عذرًا!",
  "no_internet_message":
      "لم يتم العثور على اتصال بالإنترنت. تحقق من الاتصال أو حاول مرة أخرى.",
  "try_again": "حاول مرة أخرى",
  "disconnected": "تم قطع الاتصال",
  "ongoingTask": "المهمة الجارية",
  "nextTask": "المهمة التالية",
  "upcomingTasks": "المهام القادمة",
  "today": "اليوم",
  "total": "الإجمالي",
  "upcoming": "القادمة",
  "completed": "المكتملة",
  "taskList": "قائمة المهام",
  "home": "الرئيسية",
  "user": "المستخدم",
  "lastVisited": "آخر زيارة",
  "tab_all": "الكل",
  "tab_pending": "قيد الانتظار",
  "tab_need_review": "بحاجة للمراجعة",
  "tab_approved": "تمت الموافقة",
  "tab_rejected": "مرفوض",
  "your_tasks": "مهامك",
  "your_locations": "مواقعك",
  "failed_to_connect_reader": "فشل الاتصال بالقارئ",
  "failed_to_send_tags":
      "فشل إرسال العلامات إلى واجهة برمجة التطبيقات. رمز الحالة: ",
  "error_sending_tags":
      "حدث خطأ أثناء إرسال العلامات إلى واجهة برمجة التطبيقات.",
  "error": "خطأ",
  "deleteAccount": "حذف الحساب",
  "delete": "حذف",
  "are_you_sure_delete": "هل أنت متأكد أنك تريد حذف الحساب؟",
  "personal_info": "المعلومات الشخصية",
  "logout": "تسجيل الخروج",
  "cancel": "إلغاء",
  "ok": "موافق",
  "are_you_sure_logout": "هل أنت متأكد أنك تريد تسجيل الخروج؟",
  "contact_us": "اتصل بنا",
  "terms_and_condition": "الشروط والأحكام",
  "enterMobileNumber": "أدخل رقم الجوال",
  "profile": "الملف الشخصي",
  "yourSupervisor": "مشرفك",
  "notifications": "الإشعارات",
  "filter": "تصفية",
  "applyFilter": "تطبيق التصفية",
  "start_date": "تاريخ البدء",
  "end_date": "تاريخ الانتهاء",
  "search": "بحث",
  "goodMorning": "صباح الخير",
  "goodAfternoon": "تحية العصر",
  "goodEvening": "مساء الخير",
  "goodNight": "تصبح على خير",
  "yesterday": "أمس",
  "daysAgo": "قبل @days أيام",
  "weekAgo": "قبل أسبوع واحد",
  "weeksAgo": "قبل @weeks أسابيع",
  "monthAgo": "قبل شهر واحد",
  "monthsAgo": "قبل @months أشهر",
  "yearAgo": "قبل سنة واحدة",
  "yearsAgo": "قبل @years سنوات",
  "send": "إرسال",
  "messageSent": "تم إرسال الرسالة!",
  "enterValidWeight": "أدخل وزنًا صحيحًا",
  "weWouldLoveToHearFromYou": "نود سماع آرائك!",
  "enterYourName": "أدخل اسمك",
  "enterYourEmail": "أدخل بريدك الإلكتروني",
  "enterYourMessage": "أدخل رسالتك",
  "address": "العنوان:",
  "resendOTP": "إعادة إرسال الرمز",
  "name": "الاسم",
  "email": "البريد الإلكتروني",
  "message": "الرسالة",
  "collectionData": "بيانات التجميع",
  "reset": "إعادة تعيين",
  "call": "اتصال",
  "collectedFrom": "تم التجميع من",
  "collectedFromName": "تم التجميع من (الاسم)",
  "collectedWeight": "الوزن المجمع (كجم)",
  "notesOptional": "ملاحظات (اختيارية)",
  "other": "آخر",
  "writeOtherInformationHere": "اكتب معلومات أخرى هنا",

  "typeHereToSearch": "اكتب هنا للبحث",
  "dataAgentApp": "تطبيق وكيل البيانات",
  "emailLabel": "البريد الإلكتروني",
  "mapLabel": "الخريطة",
  "pickAnotherDateRange":
      "اختر نطاق تاريخ آخر لعرض سجلات كجم المجمعة المجمعة حسب اليوم.",
  "tasks": "المهام",
  "settings": "الإعدادات",
};
