List<Map> countriesEnglish = <Map>[
  <dynamic, dynamic>{"name": "Afghanistan", "dial_code": "+93", "code": "AF"},
  <dynamic, dynamic>{
    "name": "Aland Islands",
    "dial_code": "+358",
    "code": "AX",
  },
  <dynamic, dynamic>{"name": "Albania", "dial_code": "+355", "code": "AL"},
  <dynamic, dynamic>{"name": "Algeria", "dial_code": "+213", "code": "DZ"},
  <dynamic, dynamic>{
    "name": "AmericanSamoa",
    "dial_code": "+1684",
    "code": "AS",
  },
  <dynamic, dynamic>{"name": "Andorra", "dial_code": "+376", "code": "AD"},
  <dynamic, dynamic>{"name": "Angola", "dial_code": "+244", "code": "AO"},
  <dynamic, dynamic>{"name": "Anguilla", "dial_code": "+1264", "code": "AI"},
  <dynamic, dynamic>{"name": "Antarctica", "dial_code": "+672", "code": "AQ"},
  <dynamic, dynamic>{
    "name": "Antigua and Barbuda",
    "dial_code": "+1268",
    "code": "AG",
  },
  <dynamic, dynamic>{"name": "Argentina", "dial_code": "+54", "code": "AR"},
  <dynamic, dynamic>{"name": "Armenia", "dial_code": "+374", "code": "AM"},
  <dynamic, dynamic>{"name": "Aruba", "dial_code": "+297", "code": "AW"},
  <dynamic, dynamic>{"name": "Australia", "dial_code": "+61", "code": "AU"},
  <dynamic, dynamic>{"name": "Austria", "dial_code": "+43", "code": "AT"},
  <dynamic, dynamic>{"name": "Azerbaijan", "dial_code": "+994", "code": "AZ"},
  <dynamic, dynamic>{"name": "Bahamas", "dial_code": "+1242", "code": "BS"},
  <dynamic, dynamic>{"name": "Bahrain", "dial_code": "+973", "code": "BH"},
  <dynamic, dynamic>{"name": "Bangladesh", "dial_code": "+880", "code": "BD"},
  <dynamic, dynamic>{"name": "Barbados", "dial_code": "+1246", "code": "BB"},
  <dynamic, dynamic>{"name": "Belarus", "dial_code": "+375", "code": "BY"},
  <dynamic, dynamic>{"name": "Belgium", "dial_code": "+32", "code": "BE"},
  <dynamic, dynamic>{"name": "Belize", "dial_code": "+501", "code": "BZ"},
  <dynamic, dynamic>{"name": "Benin", "dial_code": "+229", "code": "BJ"},
  <dynamic, dynamic>{"name": "Bermuda", "dial_code": "+1441", "code": "BM"},
  <dynamic, dynamic>{"name": "Bhutan", "dial_code": "+975", "code": "BT"},
  <dynamic, dynamic>{
    "name": "Bolivia, Plurinational State of",
    "dial_code": "+591",
    "code": "BO",
  },
  <dynamic, dynamic>{
    "name": "Bosnia and Herzegovina",
    "dial_code": "+387",
    "code": "BA",
  },
  <dynamic, dynamic>{"name": "Botswana", "dial_code": "+267", "code": "BW"},
  <dynamic, dynamic>{"name": "Brazil", "dial_code": "+55", "code": "BR"},
  <dynamic, dynamic>{
    "name": "British Indian Ocean Territory",
    "dial_code": "+246",
    "code": "IO",
  },
  <dynamic, dynamic>{
    "name": "Brunei Darussalam",
    "dial_code": "+673",
    "code": "BN",
  },
  <dynamic, dynamic>{"name": "Bulgaria", "dial_code": "+359", "code": "BG"},
  <dynamic, dynamic>{"name": "Burkina Faso", "dial_code": "+226", "code": "BF"},
  <dynamic, dynamic>{"name": "Burundi", "dial_code": "+257", "code": "BI"},
  <dynamic, dynamic>{"name": "Cambodia", "dial_code": "+855", "code": "KH"},
  <dynamic, dynamic>{"name": "Cameroon", "dial_code": "+237", "code": "CM"},
  <dynamic, dynamic>{"name": "Canada", "dial_code": "+1", "code": "CA"},
  <dynamic, dynamic>{"name": "Cape Verde", "dial_code": "+238", "code": "CV"},
  <dynamic, dynamic>{
    "name": "Cayman Islands",
    "dial_code": "+ 345",
    "code": "KY",
  },
  <dynamic, dynamic>{
    "name": "Central African Republic",
    "dial_code": "+236",
    "code": "CF",
  },
  <dynamic, dynamic>{"name": "Chad", "dial_code": "+235", "code": "TD"},
  <dynamic, dynamic>{"name": "Chile", "dial_code": "+56", "code": "CL"},
  <dynamic, dynamic>{"name": "China", "dial_code": "+86", "code": "CN"},
  <dynamic, dynamic>{
    "name": "Christmas Island",
    "dial_code": "+61",
    "code": "CX",
  },
  <dynamic, dynamic>{
    "name": "Cocos (Keeling) Islands",
    "dial_code": "+61",
    "code": "CC",
  },
  <dynamic, dynamic>{"name": "Colombia", "dial_code": "+57", "code": "CO"},
  <dynamic, dynamic>{"name": "Comoros", "dial_code": "+269", "code": "KM"},
  <dynamic, dynamic>{"name": "Congo", "dial_code": "+242", "code": "CG"},
  <dynamic, dynamic>{
    "name": "Congo, The Democratic Republic of the Congo",
    "dial_code": "+243",
    "code": "CD",
  },
  <dynamic, dynamic>{"name": "Cook Islands", "dial_code": "+682", "code": "CK"},
  <dynamic, dynamic>{"name": "Costa Rica", "dial_code": "+506", "code": "CR"},
  <dynamic, dynamic>{
    "name": "Cote d'Ivoire",
    "dial_code": "+225",
    "code": "CI",
  },
  <dynamic, dynamic>{"name": "Croatia", "dial_code": "+385", "code": "HR"},
  <dynamic, dynamic>{"name": "Cuba", "dial_code": "+53", "code": "CU"},
  <dynamic, dynamic>{"name": "Cyprus", "dial_code": "+357", "code": "CY"},
  <dynamic, dynamic>{
    "name": "Czech Republic",
    "dial_code": "+420",
    "code": "CZ",
  },
  <dynamic, dynamic>{"name": "Denmark", "dial_code": "+45", "code": "DK"},
  <dynamic, dynamic>{"name": "Djibouti", "dial_code": "+253", "code": "DJ"},
  <dynamic, dynamic>{"name": "Dominica", "dial_code": "+1767", "code": "DM"},
  <dynamic, dynamic>{
    "name": "Dominican Republic",
    "dial_code": "+1849",
    "code": "DO",
  },
  <dynamic, dynamic>{"name": "Ecuador", "dial_code": "+593", "code": "EC"},
  <dynamic, dynamic>{"name": "Egypt", "dial_code": "+20", "code": "EG"},
  <dynamic, dynamic>{"name": "El Salvador", "dial_code": "+503", "code": "SV"},
  <dynamic, dynamic>{
    "name": "Equatorial Guinea",
    "dial_code": "+240",
    "code": "GQ",
  },
  <dynamic, dynamic>{"name": "Eritrea", "dial_code": "+291", "code": "ER"},
  <dynamic, dynamic>{"name": "Estonia", "dial_code": "+372", "code": "EE"},
  <dynamic, dynamic>{"name": "Ethiopia", "dial_code": "+251", "code": "ET"},
  <dynamic, dynamic>{
    "name": "Falkland Islands (Malvinas)",
    "dial_code": "+500",
    "code": "FK",
  },
  <dynamic, dynamic>{
    "name": "Faroe Islands",
    "dial_code": "+298",
    "code": "FO",
  },
  <dynamic, dynamic>{"name": "Fiji", "dial_code": "+679", "code": "FJ"},
  <dynamic, dynamic>{"name": "Finland", "dial_code": "+358", "code": "FI"},
  <dynamic, dynamic>{"name": "France", "dial_code": "+33", "code": "FR"},
  <dynamic, dynamic>{
    "name": "French Guiana",
    "dial_code": "+594",
    "code": "GF",
  },
  <dynamic, dynamic>{
    "name": "French Polynesia",
    "dial_code": "+689",
    "code": "PF",
  },
  <dynamic, dynamic>{"name": "Gabon", "dial_code": "+241", "code": "GA"},
  <dynamic, dynamic>{"name": "Gambia", "dial_code": "+220", "code": "GM"},
  <dynamic, dynamic>{"name": "Georgia", "dial_code": "+995", "code": "GE"},
  <dynamic, dynamic>{"name": "Germany", "dial_code": "+49", "code": "DE"},
  <dynamic, dynamic>{"name": "Ghana", "dial_code": "+233", "code": "GH"},
  <dynamic, dynamic>{"name": "Gibraltar", "dial_code": "+350", "code": "GI"},
  <dynamic, dynamic>{"name": "Greece", "dial_code": "+30", "code": "GR"},
  <dynamic, dynamic>{"name": "Greenland", "dial_code": "+299", "code": "GL"},
  <dynamic, dynamic>{"name": "Grenada", "dial_code": "+1473", "code": "GD"},
  <dynamic, dynamic>{"name": "Guadeloupe", "dial_code": "+590", "code": "GP"},
  <dynamic, dynamic>{"name": "Guam", "dial_code": "+1671", "code": "GU"},
  <dynamic, dynamic>{"name": "Guatemala", "dial_code": "+502", "code": "GT"},
  <dynamic, dynamic>{"name": "Guernsey", "dial_code": "+44", "code": "GG"},
  <dynamic, dynamic>{"name": "Guinea", "dial_code": "+224", "code": "GN"},
  <dynamic, dynamic>{
    "name": "Guinea-Bissau",
    "dial_code": "+245",
    "code": "GW",
  },
  <dynamic, dynamic>{"name": "Guyana", "dial_code": "+595", "code": "GY"},
  <dynamic, dynamic>{"name": "Haiti", "dial_code": "+509", "code": "HT"},
  <dynamic, dynamic>{
    "name": "Holy See (Vatican City State)",
    "dial_code": "+379",
    "code": "VA",
  },
  <dynamic, dynamic>{"name": "Honduras", "dial_code": "+504", "code": "HN"},
  <dynamic, dynamic>{"name": "Hong Kong", "dial_code": "+852", "code": "HK"},
  <dynamic, dynamic>{"name": "Hungary", "dial_code": "+36", "code": "HU"},
  <dynamic, dynamic>{"name": "Iceland", "dial_code": "+354", "code": "IS"},
  <dynamic, dynamic>{"name": "India", "dial_code": "+91", "code": "IN"},
  <dynamic, dynamic>{"name": "Indonesia", "dial_code": "+62", "code": "ID"},
  <dynamic, dynamic>{
    "name": "Iran, Islamic Republic of Persian Gulf",
    "dial_code": "+98",
    "code": "IR",
  },
  <dynamic, dynamic>{"name": "Iraq", "dial_code": "+964", "code": "IQ"},
  <dynamic, dynamic>{"name": "Ireland", "dial_code": "+353", "code": "IE"},
  <dynamic, dynamic>{"name": "Isle of Man", "dial_code": "+44", "code": "IM"},
  <dynamic, dynamic>{"name": "Israel", "dial_code": "+972", "code": "IL"},
  <dynamic, dynamic>{"name": "Italy", "dial_code": "+39", "code": "IT"},
  <dynamic, dynamic>{"name": "Jamaica", "dial_code": "+1876", "code": "JM"},
  <dynamic, dynamic>{"name": "Japan", "dial_code": "+81", "code": "JP"},
  <dynamic, dynamic>{"name": "Jersey", "dial_code": "+44", "code": "JE"},
  <dynamic, dynamic>{"name": "Jordan", "dial_code": "+962", "code": "JO"},
  <dynamic, dynamic>{"name": "Kazakhstan", "dial_code": "+77", "code": "KZ"},
  <dynamic, dynamic>{"name": "Kenya", "dial_code": "+254", "code": "KE"},
  <dynamic, dynamic>{"name": "Kiribati", "dial_code": "+686", "code": "KI"},
  <dynamic, dynamic>{
    "name": "Korea, Democratic People's Republic of Korea",
    "dial_code": "+850",
    "code": "KP",
  },
  <dynamic, dynamic>{
    "name": "Korea, Republic of South Korea",
    "dial_code": "+82",
    "code": "KR",
  },
  <dynamic, dynamic>{"name": "Kuwait", "dial_code": "+965", "code": "KW"},
  <dynamic, dynamic>{"name": "Kyrgyzstan", "dial_code": "+996", "code": "KG"},
  <dynamic, dynamic>{"name": "Laos", "dial_code": "+856", "code": "LA"},
  <dynamic, dynamic>{"name": "Latvia", "dial_code": "+371", "code": "LV"},
  <dynamic, dynamic>{"name": "Lebanon", "dial_code": "+961", "code": "LB"},
  <dynamic, dynamic>{"name": "Lesotho", "dial_code": "+266", "code": "LS"},
  <dynamic, dynamic>{"name": "Liberia", "dial_code": "+231", "code": "LR"},
  <dynamic, dynamic>{
    "name": "Libyan Arab Jamahiriya",
    "dial_code": "+218",
    "code": "LY",
  },
  <dynamic, dynamic>{
    "name": "Liechtenstein",
    "dial_code": "+423",
    "code": "LI",
  },
  <dynamic, dynamic>{"name": "Lithuania", "dial_code": "+370", "code": "LT"},
  <dynamic, dynamic>{"name": "Luxembourg", "dial_code": "+352", "code": "LU"},
  <dynamic, dynamic>{"name": "Macao", "dial_code": "+853", "code": "MO"},
  <dynamic, dynamic>{"name": "Macedonia", "dial_code": "+389", "code": "MK"},
  <dynamic, dynamic>{"name": "Madagascar", "dial_code": "+261", "code": "MG"},
  <dynamic, dynamic>{"name": "Malawi", "dial_code": "+265", "code": "MW"},
  <dynamic, dynamic>{"name": "Malaysia", "dial_code": "+60", "code": "MY"},
  <dynamic, dynamic>{"name": "Maldives", "dial_code": "+960", "code": "MV"},
  <dynamic, dynamic>{"name": "Mali", "dial_code": "+223", "code": "ML"},
  <dynamic, dynamic>{"name": "Malta", "dial_code": "+356", "code": "MT"},
  <dynamic, dynamic>{
    "name": "Marshall Islands",
    "dial_code": "+692",
    "code": "MH",
  },
  <dynamic, dynamic>{"name": "Martinique", "dial_code": "+596", "code": "MQ"},
  <dynamic, dynamic>{"name": "Mauritania", "dial_code": "+222", "code": "MR"},
  <dynamic, dynamic>{"name": "Mauritius", "dial_code": "+230", "code": "MU"},
  <dynamic, dynamic>{"name": "Mayotte", "dial_code": "+262", "code": "YT"},
  <dynamic, dynamic>{"name": "Mexico", "dial_code": "+52", "code": "MX"},
  <dynamic, dynamic>{
    "name": "Micronesia, Federated States of Micronesia",
    "dial_code": "+691",
    "code": "FM",
  },
  <dynamic, dynamic>{"name": "Moldova", "dial_code": "+373", "code": "MD"},
  <dynamic, dynamic>{"name": "Monaco", "dial_code": "+377", "code": "MC"},
  <dynamic, dynamic>{"name": "Mongolia", "dial_code": "+976", "code": "MN"},
  <dynamic, dynamic>{"name": "Montenegro", "dial_code": "+382", "code": "ME"},
  <dynamic, dynamic>{"name": "Montserrat", "dial_code": "+1664", "code": "MS"},
  <dynamic, dynamic>{"name": "Morocco", "dial_code": "+212", "code": "MA"},
  <dynamic, dynamic>{"name": "Mozambique", "dial_code": "+258", "code": "MZ"},
  <dynamic, dynamic>{"name": "Myanmar", "dial_code": "+95", "code": "MM"},
  <dynamic, dynamic>{"name": "Namibia", "dial_code": "+264", "code": "NA"},
  <dynamic, dynamic>{"name": "Nauru", "dial_code": "+674", "code": "NR"},
  <dynamic, dynamic>{"name": "Nepal", "dial_code": "+977", "code": "NP"},
  <dynamic, dynamic>{"name": "Netherlands", "dial_code": "+31", "code": "NL"},
  <dynamic, dynamic>{
    "name": "Netherlands Antilles",
    "dial_code": "+599",
    "code": "AN",
  },
  <dynamic, dynamic>{
    "name": "New Caledonia",
    "dial_code": "+687",
    "code": "NC",
  },
  <dynamic, dynamic>{"name": "New Zealand", "dial_code": "+64", "code": "NZ"},
  <dynamic, dynamic>{"name": "Nicaragua", "dial_code": "+505", "code": "NI"},
  <dynamic, dynamic>{"name": "Niger", "dial_code": "+227", "code": "NE"},
  <dynamic, dynamic>{"name": "Nigeria", "dial_code": "+234", "code": "NG"},
  <dynamic, dynamic>{"name": "Niue", "dial_code": "+683", "code": "NU"},
  <dynamic, dynamic>{
    "name": "Norfolk Island",
    "dial_code": "+672",
    "code": "NF",
  },
  <dynamic, dynamic>{
    "name": "Northern Mariana Islands",
    "dial_code": "+1670",
    "code": "MP",
  },
  <dynamic, dynamic>{"name": "Norway", "dial_code": "+47", "code": "NO"},
  <dynamic, dynamic>{"name": "Oman", "dial_code": "+968", "code": "OM"},
  <dynamic, dynamic>{"name": "Pakistan", "dial_code": "+92", "code": "PK"},
  <dynamic, dynamic>{"name": "Palau", "dial_code": "+680", "code": "PW"},
  <dynamic, dynamic>{
    "name": "Palestinian Territory, Occupied",
    "dial_code": "+970",
    "code": "PS",
  },
  <dynamic, dynamic>{"name": "Panama", "dial_code": "+507", "code": "PA"},
  <dynamic, dynamic>{
    "name": "Papua New Guinea",
    "dial_code": "+675",
    "code": "PG",
  },
  <dynamic, dynamic>{"name": "Paraguay", "dial_code": "+595", "code": "PY"},
  <dynamic, dynamic>{"name": "Peru", "dial_code": "+51", "code": "PE"},
  <dynamic, dynamic>{"name": "Philippines", "dial_code": "+63", "code": "PH"},
  <dynamic, dynamic>{"name": "Pitcairn", "dial_code": "+872", "code": "PN"},
  <dynamic, dynamic>{"name": "Poland", "dial_code": "+48", "code": "PL"},
  <dynamic, dynamic>{"name": "Portugal", "dial_code": "+351", "code": "PT"},
  <dynamic, dynamic>{"name": "Puerto Rico", "dial_code": "+1939", "code": "PR"},
  <dynamic, dynamic>{"name": "Qatar", "dial_code": "+974", "code": "QA"},
  <dynamic, dynamic>{"name": "Romania", "dial_code": "+40", "code": "RO"},
  <dynamic, dynamic>{"name": "Russia", "dial_code": "+7", "code": "RU"},
  <dynamic, dynamic>{"name": "Rwanda", "dial_code": "+250", "code": "RW"},
  <dynamic, dynamic>{"name": "Reunion", "dial_code": "+262", "code": "RE"},
  <dynamic, dynamic>{
    "name": "Saint Barthelemy",
    "dial_code": "+590",
    "code": "BL",
  },
  <dynamic, dynamic>{
    "name": "Saint Helena, Ascension and Tristan Da Cunha",
    "dial_code": "+290",
    "code": "SH",
  },
  <dynamic, dynamic>{
    "name": "Saint Kitts and Nevis",
    "dial_code": "+1869",
    "code": "KN",
  },
  <dynamic, dynamic>{"name": "Saint Lucia", "dial_code": "+1758", "code": "LC"},
  <dynamic, dynamic>{"name": "Saint Martin", "dial_code": "+590", "code": "MF"},
  <dynamic, dynamic>{
    "name": "Saint Pierre and Miquelon",
    "dial_code": "+508",
    "code": "PM",
  },
  <dynamic, dynamic>{
    "name": "Saint Vincent and the Grenadines",
    "dial_code": "+1784",
    "code": "VC",
  },
  <dynamic, dynamic>{"name": "Samoa", "dial_code": "+685", "code": "WS"},
  <dynamic, dynamic>{"name": "San Marino", "dial_code": "+378", "code": "SM"},
  <dynamic, dynamic>{
    "name": "Sao Tome and Principe",
    "dial_code": "+239",
    "code": "ST",
  },
  <dynamic, dynamic>{"name": "Saudi Arabia", "dial_code": "+966", "code": "SA"},
  <dynamic, dynamic>{"name": "Senegal", "dial_code": "+221", "code": "SN"},
  <dynamic, dynamic>{"name": "Serbia", "dial_code": "+381", "code": "RS"},
  <dynamic, dynamic>{"name": "Seychelles", "dial_code": "+248", "code": "SC"},
  <dynamic, dynamic>{"name": "Sierra Leone", "dial_code": "+232", "code": "SL"},
  <dynamic, dynamic>{"name": "Singapore", "dial_code": "+65", "code": "SG"},
  <dynamic, dynamic>{"name": "Slovakia", "dial_code": "+421", "code": "SK"},
  <dynamic, dynamic>{"name": "Slovenia", "dial_code": "+386", "code": "SI"},
  <dynamic, dynamic>{
    "name": "Solomon Islands",
    "dial_code": "+677",
    "code": "SB",
  },
  <dynamic, dynamic>{"name": "Somalia", "dial_code": "+252", "code": "SO"},
  <dynamic, dynamic>{"name": "South Africa", "dial_code": "+27", "code": "ZA"},
  <dynamic, dynamic>{"name": "South Sudan", "dial_code": "+211", "code": "SS"},
  <dynamic, dynamic>{
    "name": "South Georgia and the South Sandwich Islands",
    "dial_code": "+500",
    "code": "GS",
  },
  <dynamic, dynamic>{"name": "Spain", "dial_code": "+34", "code": "ES"},
  <dynamic, dynamic>{"name": "Sri Lanka", "dial_code": "+94", "code": "LK"},
  <dynamic, dynamic>{"name": "Sudan", "dial_code": "+249", "code": "SD"},
  <dynamic, dynamic>{"name": "Suriname", "dial_code": "+597", "code": "SR"},
  <dynamic, dynamic>{
    "name": "Svalbard and Jan Mayen",
    "dial_code": "+47",
    "code": "SJ",
  },
  <dynamic, dynamic>{"name": "Swaziland", "dial_code": "+268", "code": "SZ"},
  <dynamic, dynamic>{"name": "Sweden", "dial_code": "+46", "code": "SE"},
  <dynamic, dynamic>{"name": "Switzerland", "dial_code": "+41", "code": "CH"},
  <dynamic, dynamic>{
    "name": "Syrian Arab Republic",
    "dial_code": "+963",
    "code": "SY",
  },
  <dynamic, dynamic>{"name": "Taiwan", "dial_code": "+886", "code": "TW"},
  <dynamic, dynamic>{"name": "Tajikistan", "dial_code": "+992", "code": "TJ"},
  <dynamic, dynamic>{
    "name": "Tanzania, United Republic of Tanzania",
    "dial_code": "+255",
    "code": "TZ",
  },
  <dynamic, dynamic>{"name": "Thailand", "dial_code": "+66", "code": "TH"},
  <dynamic, dynamic>{"name": "Timor-Leste", "dial_code": "+670", "code": "TL"},
  <dynamic, dynamic>{"name": "Togo", "dial_code": "+228", "code": "TG"},
  <dynamic, dynamic>{"name": "Tokelau", "dial_code": "+690", "code": "TK"},
  <dynamic, dynamic>{"name": "Tonga", "dial_code": "+676", "code": "TO"},
  <dynamic, dynamic>{
    "name": "Trinidad and Tobago",
    "dial_code": "+1868",
    "code": "TT",
  },
  <dynamic, dynamic>{"name": "Tunisia", "dial_code": "+216", "code": "TN"},
  <dynamic, dynamic>{"name": "Turkey", "dial_code": "+90", "code": "TR"},
  <dynamic, dynamic>{"name": "Turkmenistan", "dial_code": "+993", "code": "TM"},
  <dynamic, dynamic>{
    "name": "Turks and Caicos Islands",
    "dial_code": "+1649",
    "code": "TC",
  },
  <dynamic, dynamic>{"name": "Tuvalu", "dial_code": "+688", "code": "TV"},
  <dynamic, dynamic>{"name": "Uganda", "dial_code": "+256", "code": "UG"},
  <dynamic, dynamic>{"name": "Ukraine", "dial_code": "+380", "code": "UA"},
  <dynamic, dynamic>{
    "name": "United Arab Emirates",
    "dial_code": "+971",
    "code": "AE",
  },
  <dynamic, dynamic>{
    "name": "United Kingdom",
    "dial_code": "+44",
    "code": "GB",
  },
  <dynamic, dynamic>{"name": "United States", "dial_code": "+1", "code": "US"},
  <dynamic, dynamic>{"name": "Uruguay", "dial_code": "+598", "code": "UY"},
  <dynamic, dynamic>{"name": "Uzbekistan", "dial_code": "+998", "code": "UZ"},
  <dynamic, dynamic>{"name": "Vanuatu", "dial_code": "+678", "code": "VU"},
  <dynamic, dynamic>{
    "name": "Venezuela, Bolivarian Republic of Venezuela",
    "dial_code": "+58",
    "code": "VE",
  },
  <dynamic, dynamic>{"name": "Vietnam", "dial_code": "+84", "code": "VN"},
  <dynamic, dynamic>{
    "name": "Virgin Islands, British",
    "dial_code": "+1284",
    "code": "VG",
  },
  <dynamic, dynamic>{
    "name": "Virgin Islands, U.S.",
    "dial_code": "+1340",
    "code": "VI",
  },
  <dynamic, dynamic>{
    "name": "Wallis and Futuna",
    "dial_code": "+681",
    "code": "WF",
  },
  <dynamic, dynamic>{"name": "Yemen", "dial_code": "+967", "code": "YE"},
  <dynamic, dynamic>{"name": "Zambia", "dial_code": "+260", "code": "ZM"},
  <dynamic, dynamic>{"name": "Zimbabwe", "dial_code": "+263", "code": "ZW"},
];
